import type {Comment, Post, Subreddit, User} from '../types';

const NOW = Date.now() / 1000;
const mins = (n: number) => NOW - n * 60;
const hours = (n: number) => NOW - n * 3600;
const days = (n: number) => NOW - n * 86400;

// ─── User ─────────────────────────────────────────────────────────────────────

export const MOCK_USER: User = {
  id: 'abc123',
  name: 'redditor_mc_face',
  iconImg: null,
  karma: 14823,
  commentKarma: 9201,
  linkKarma: 5622,
  created: days(730),
  isGold: false,
  isMod: false,
};

// ─── Subreddits ───────────────────────────────────────────────────────────────

export const MOCK_SUBREDDITS: Subreddit[] = [
  {
    id: 'sub1',
    name: 't5_2fwo',
    displayName: 'programming',
    title: 'programming',
    description: 'Computer Programming',
    public_description: 'Computer Programming news, discussion and projects.',
    subscribers: 6_200_000,
    iconImg: null,
    bannerImg: null,
    primaryColor: '#ff4500',
    isSubscribed: true,
    over18: false,
    created_utc: days(5000),
    url: '/r/programming/',
  },
  {
    id: 'sub2',
    name: 't5_2qh13',
    displayName: 'worldnews',
    title: 'worldnews',
    description: 'A place for major news from around the world.',
    public_description: 'A place for major news from around the world.',
    subscribers: 31_000_000,
    iconImg: null,
    bannerImg: null,
    primaryColor: '#0dd3bb',
    isSubscribed: true,
    over18: false,
    created_utc: days(6000),
    url: '/r/worldnews/',
  },
  {
    id: 'sub3',
    name: 't5_2qh33',
    displayName: 'funny',
    title: 'funny',
    description: 'Welcome to r/Funny, Reddit\'s largest humour depository.',
    public_description: 'Welcome to r/Funny, Reddit\'s largest humour depository.',
    subscribers: 58_000_000,
    iconImg: null,
    bannerImg: null,
    primaryColor: '#ffd635',
    isSubscribed: true,
    over18: false,
    created_utc: days(7000),
    url: '/r/funny/',
  },
  {
    id: 'sub4',
    name: 't5_2qh2',
    displayName: 'gaming',
    title: 'gaming',
    description: 'A subreddit for gamers.',
    public_description: 'A subreddit for (almost) anything related to games.',
    subscribers: 40_000_000,
    iconImg: null,
    bannerImg: null,
    primaryColor: '#7193ff',
    isSubscribed: true,
    over18: false,
    created_utc: days(6500),
    url: '/r/gaming/',
  },
  {
    id: 'sub5',
    name: 't5_mouw',
    displayName: 'science',
    title: 'science',
    description: 'Reddit\'s home for science.',
    public_description: 'Science news and discussions.',
    subscribers: 32_000_000,
    iconImg: null,
    bannerImg: null,
    primaryColor: '#46d160',
    isSubscribed: true,
    over18: false,
    created_utc: days(5500),
    url: '/r/science/',
  },
  {
    id: 'sub6',
    name: 't5_2qh0u',
    displayName: 'pics',
    title: 'pics',
    description: 'A place for pictures.',
    public_description: 'A place for pictures and photographs.',
    subscribers: 30_000_000,
    iconImg: null,
    bannerImg: null,
    primaryColor: null,
    isSubscribed: false,
    over18: false,
    created_utc: days(6000),
    url: '/r/pics/',
  },
  {
    id: 'sub7',
    name: 't5_askreddit',
    displayName: 'AskReddit',
    title: 'AskReddit',
    description: 'Ask and answer questions.',
    public_description: 'Ask Reddit anything.',
    subscribers: 45_000_000,
    iconImg: null,
    bannerImg: null,
    primaryColor: '#ff585b',
    isSubscribed: false,
    over18: false,
    created_utc: days(5800),
    url: '/r/AskReddit/',
  },
  {
    id: 'sub8',
    name: 't5_todayilearned',
    displayName: 'todayilearned',
    title: 'Today I Learned',
    description: 'You learn something new every day.',
    public_description: 'You learn something new every day; what did you learn today?',
    subscribers: 38_000_000,
    iconImg: null,
    bannerImg: null,
    primaryColor: '#d4e815',
    isSubscribed: false,
    over18: false,
    created_utc: days(5200),
    url: '/r/todayilearned/',
  },
];

// ─── Posts ────────────────────────────────────────────────────────────────────

export const MOCK_POSTS: Post[] = [
  {
    id: 'post1',
    title: 'I built a full-stack app in a weekend using only open-source tools — here\'s what I learned',
    author: 'dev_weekend_warrior',
    subreddit: 'programming',
    subreddit_name_prefixed: 'r/programming',
    score: 18423,
    numComments: 342,
    url: 'https://example.com/fullstack-weekend',
    thumbnail: null,
    selftext: 'After years of wanting to build something complete, I finally sat down and built a project tracker over one weekend. Here\'s a breakdown of the stack and the painful lessons along the way.\n\n## The Stack\n- Frontend: React + Vite\n- Backend: FastAPI (Python)\n- Database: SQLite → Postgres\n- Auth: Lucia (sessions, not JWTs)\n- Hosting: Fly.io\n\n## What went wrong\n\nAuth took 4x longer than expected. I kept fighting with cookie SameSite settings. The real lesson: always prototype auth first.',
    isRead: false,
    created_utc: hours(3),
    post_hint: 'self',
    permalink: '/r/programming/comments/post1/i_built_a_fullstack_app/',
    is_self: true,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.97,
    likes: null,
  },
  {
    id: 'post2',
    title: 'Scientists discover material that conducts electricity at room temperature with near-zero resistance',
    author: 'physics_breakthroughs',
    subreddit: 'science',
    subreddit_name_prefixed: 'r/science',
    score: 52110,
    numComments: 1823,
    url: 'https://example.com/room-temp-superconductor',
    thumbnail: null,
    selftext: '',
    isRead: false,
    created_utc: hours(6),
    post_hint: 'link',
    permalink: '/r/science/comments/post2/scientists_discover/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.94,
    likes: null,
  },
  {
    id: 'post3',
    title: 'My dog learned to open doors and now nothing is sacred',
    author: 'suburban_chaos_mom',
    subreddit: 'funny',
    subreddit_name_prefixed: 'r/funny',
    score: 89432,
    numComments: 2104,
    url: 'https://example.com/dog-opens-doors.jpg',
    thumbnail: 'https://picsum.photos/seed/dog1/140/100',
    selftext: '',
    isRead: true,
    created_utc: hours(12),
    post_hint: 'image',
    permalink: '/r/funny/comments/post3/my_dog_learned/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.98,
    likes: true,
    preview: {
      images: [{
        source: {url: 'https://picsum.photos/seed/dog1/800/600', width: 800, height: 600},
        resolutions: [
          {url: 'https://picsum.photos/seed/dog1/320/240', width: 320, height: 240},
          {url: 'https://picsum.photos/seed/dog1/640/480', width: 640, height: 480},
        ],
      }],
    },
  },
  {
    id: 'post4',
    title: 'After 20 years, Valve finally updates the Steam client UI and it\'s... actually good?',
    author: 'pcgaming_veteran',
    subreddit: 'gaming',
    subreddit_name_prefixed: 'r/gaming',
    score: 34901,
    numComments: 987,
    url: 'https://example.com/steam-ui-update',
    thumbnail: 'https://picsum.photos/seed/steam1/140/100',
    selftext: '',
    isRead: false,
    created_utc: hours(8),
    post_hint: 'link',
    permalink: '/r/gaming/comments/post4/after_20_years/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.91,
    likes: null,
  },
  {
    id: 'post5',
    title: 'EU passes sweeping AI regulation bill requiring transparency in all automated decision systems',
    author: 'tech_policy_watch',
    subreddit: 'worldnews',
    subreddit_name_prefixed: 'r/worldnews',
    score: 27880,
    numComments: 2341,
    url: 'https://example.com/eu-ai-regulation',
    thumbnail: null,
    selftext: '',
    isRead: false,
    created_utc: hours(5),
    post_hint: 'link',
    permalink: '/r/worldnews/comments/post5/eu_passes_ai_regulation/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.86,
    likes: null,
  },
  {
    id: 'post6',
    title: 'TypeScript 6.0 is out — what\'s new and what broke',
    author: 'ts_enthusiast_99',
    subreddit: 'programming',
    subreddit_name_prefixed: 'r/programming',
    score: 9201,
    numComments: 431,
    url: 'https://example.com/typescript-6',
    thumbnail: null,
    selftext: 'The TypeScript team just dropped 6.0 and as usual there are a few breaking changes buried under all the shiny new features. Let\'s go through what matters.\n\n**New features**\n- Isolated modules by default\n- Improved type narrowing in switch statements\n- Native `using` declarations (finally stable)\n\n**Breaking changes**\n- `noImplicitAny` is now `true` by default in strict mode\n- Some `lib.d.ts` types were tightened\n\nMigration from 5.x is mostly painless if you\'re already on strict mode.',
    isRead: false,
    created_utc: hours(9),
    post_hint: 'self',
    permalink: '/r/programming/comments/post6/typescript_60/',
    is_self: true,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.93,
    likes: null,
  },
  {
    id: 'post7',
    title: 'I asked my 8-year-old to draw "what the internet looks like" and I think they might be onto something',
    author: 'dad_jokes_and_more',
    subreddit: 'funny',
    subreddit_name_prefixed: 'r/funny',
    score: 124500,
    numComments: 3210,
    url: 'https://example.com/kid-draws-internet.jpg',
    thumbnail: 'https://picsum.photos/seed/kidart/140/100',
    selftext: '',
    isRead: false,
    created_utc: days(1),
    post_hint: 'image',
    permalink: '/r/funny/comments/post7/my_kid_drew/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.99,
    likes: null,
    preview: {
      images: [{
        source: {url: 'https://picsum.photos/seed/kidart/600/800', width: 600, height: 800},
        resolutions: [
          {url: 'https://picsum.photos/seed/kidart/300/400', width: 300, height: 400},
        ],
      }],
    },
  },
  {
    id: 'post8',
    title: 'New study finds that regular breaks during coding sessions improve output quality by 23%',
    author: 'productivity_research',
    subreddit: 'programming',
    subreddit_name_prefixed: 'r/programming',
    score: 11203,
    numComments: 298,
    url: 'https://example.com/coding-breaks-study',
    thumbnail: null,
    selftext: '',
    isRead: true,
    created_utc: hours(14),
    post_hint: 'link',
    permalink: '/r/programming/comments/post8/breaks_improve_coding/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.88,
    likes: null,
  },
  {
    id: 'post9',
    title: 'Game dev who went solo after leaving AAA studio: "I make less money and have never been happier"',
    author: 'indie_dev_stories',
    subreddit: 'gaming',
    subreddit_name_prefixed: 'r/gaming',
    score: 62300,
    numComments: 1102,
    url: 'https://example.com/indie-dev-interview',
    thumbnail: null,
    selftext: '',
    isRead: false,
    created_utc: hours(16),
    post_hint: 'link',
    permalink: '/r/gaming/comments/post9/solo_dev_interview/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.96,
    likes: null,
  },
  {
    id: 'post10',
    title: 'Researchers grow functional brain organoids that respond to light stimuli',
    author: 'neuro_frontier',
    subreddit: 'science',
    subreddit_name_prefixed: 'r/science',
    score: 38200,
    numComments: 892,
    url: 'https://example.com/brain-organoids',
    thumbnail: null,
    selftext: '',
    isRead: false,
    created_utc: days(1),
    post_hint: 'link',
    permalink: '/r/science/comments/post10/brain_organoids/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.92,
    likes: null,
  },
  {
    id: 'post11',
    title: 'Show HN: I rebuilt grep in Rust and it\'s 4x faster on large repos',
    author: 'rust_evangelist_42',
    subreddit: 'programming',
    subreddit_name_prefixed: 'r/programming',
    score: 7830,
    numComments: 562,
    url: 'https://github.com/example/rgrep',
    thumbnail: null,
    selftext: '',
    isRead: false,
    created_utc: hours(20),
    post_hint: 'link',
    permalink: '/r/programming/comments/post11/rust_grep/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.89,
    likes: null,
  },
  {
    id: 'post12',
    title: 'The face my cat makes when I close my laptop after being on it all day',
    author: 'wfh_cat_parent',
    subreddit: 'funny',
    subreddit_name_prefixed: 'r/funny',
    score: 77100,
    numComments: 1893,
    url: 'https://example.com/cat-laptop.jpg',
    thumbnail: 'https://picsum.photos/seed/cat1/140/100',
    selftext: '',
    isRead: false,
    created_utc: days(2),
    post_hint: 'image',
    permalink: '/r/funny/comments/post12/cat_laptop/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.97,
    likes: null,
    preview: {
      images: [{
        source: {url: 'https://picsum.photos/seed/cat1/700/700', width: 700, height: 700},
        resolutions: [
          {url: 'https://picsum.photos/seed/cat1/350/350', width: 350, height: 350},
        ],
      }],
    },
  },
];

// Second page of posts for pagination simulation
export const MOCK_POSTS_PAGE2: Post[] = [
  {
    id: 'post13',
    title: 'Why I switched from Vim to Neovim and what I use now',
    author: 'keyboard_philosopher',
    subreddit: 'programming',
    subreddit_name_prefixed: 'r/programming',
    score: 5421,
    numComments: 712,
    url: 'https://example.com/vim-neovim',
    thumbnail: null,
    selftext: 'Hot take: the Neovim ecosystem has matured enough that it\'s actually a pleasure to use. Here\'s my config and why I landed here after years of editor-hopping.',
    isRead: false,
    created_utc: days(3),
    post_hint: 'self',
    permalink: '/r/programming/comments/post13/vim_neovim/',
    is_self: true,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.87,
    likes: null,
  },
  {
    id: 'post14',
    title: 'Ocean cleanup project removes 100,000 kg of plastic from Pacific in single expedition',
    author: 'climate_good_news',
    subreddit: 'worldnews',
    subreddit_name_prefixed: 'r/worldnews',
    score: 44800,
    numComments: 1204,
    url: 'https://example.com/ocean-cleanup',
    thumbnail: null,
    selftext: '',
    isRead: false,
    created_utc: days(2),
    post_hint: 'link',
    permalink: '/r/worldnews/comments/post14/ocean_cleanup/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.95,
    likes: null,
  },
  {
    id: 'post15',
    title: 'My first game jam entry after 3 years of "learning Unity someday"',
    author: 'finally_shipped_something',
    subreddit: 'gaming',
    subreddit_name_prefixed: 'r/gaming',
    score: 28900,
    numComments: 834,
    url: 'https://example.com/game-jam-entry',
    thumbnail: 'https://picsum.photos/seed/gamejam/140/100',
    selftext: '',
    isRead: false,
    created_utc: days(2),
    post_hint: 'image',
    permalink: '/r/gaming/comments/post15/first_game_jam/',
    is_self: false,
    over_18: false,
    stickied: false,
    upvote_ratio: 0.98,
    likes: null,
    preview: {
      images: [{
        source: {url: 'https://picsum.photos/seed/gamejam/800/500', width: 800, height: 500},
        resolutions: [
          {url: 'https://picsum.photos/seed/gamejam/400/250', width: 400, height: 250},
        ],
      }],
    },
  },
];

// ─── Comments ─────────────────────────────────────────────────────────────────

function makeComments(postId: string): Comment[] {
  const templates: Comment[] = [
    {
      id: `${postId}_c1`,
      author: 'senior_dev_opinions',
      body: 'This is exactly the kind of experience report we need more of. Too much content online is either "look how easy this is" tutorials or impenetrable academic papers. The middle ground — real project retrospectives — is gold.',
      score: 1842,
      replies: [
        {
          id: `${postId}_c1_r1`,
          author: 'junior_dev_2023',
          body: 'Agreed. I learned more from this post than from three courses I paid for.',
          score: 420,
          replies: [],
          depth: 1,
          created_utc: mins(45),
          likes: null,
          is_submitter: false,
          distinguished: null,
          stickied: false,
          collapsed: false,
        },
        {
          id: `${postId}_c1_r2`,
          author: 'pragmatic_pete',
          body: 'There\'s a whole genre of "things I wish I knew" posts that are consistently the most-upvoted content on this sub. The wisdom is in the scars.',
          score: 312,
          replies: [
            {
              id: `${postId}_c1_r2_r1`,
              author: 'senior_dev_opinions',
              body: 'Exactly. Failure is underrated as a learning mechanism.',
              score: 201,
              replies: [],
              depth: 2,
              created_utc: mins(30),
              likes: null,
              is_submitter: false,
              distinguished: null,
              stickied: false,
              collapsed: false,
            },
          ],
          depth: 1,
          created_utc: mins(40),
          likes: null,
          is_submitter: false,
          distinguished: null,
          stickied: false,
          collapsed: false,
        },
      ],
      depth: 0,
      created_utc: hours(2),
      likes: null,
      is_submitter: false,
      distinguished: null,
      stickied: false,
      collapsed: false,
    },
    {
      id: `${postId}_c2`,
      author: 'auth_skeptic',
      body: 'Auth always takes 4x longer than estimated. I\'ve started multiplying my auth time estimate by 10 and I\'m still usually wrong.',
      score: 934,
      replies: [
        {
          id: `${postId}_c2_r1`,
          author: 'op_here',
          body: 'I should have known. Every senior dev I talked to said "auth is the hardest part" and I nodded like I understood. I did not understand.',
          score: 712,
          replies: [],
          depth: 1,
          created_utc: hours(1),
          likes: null,
          is_submitter: true,
          distinguished: null,
          stickied: false,
          collapsed: false,
        },
      ],
      depth: 0,
      created_utc: hours(2),
      likes: null,
      is_submitter: false,
      distinguished: null,
      stickied: false,
      collapsed: false,
    },
    {
      id: `${postId}_c3`,
      author: 'fly_io_fan',
      body: 'Fly.io is underrated for projects like this. The free tier is generous and the DX is miles ahead of other options. Good choice.',
      score: 521,
      replies: [],
      depth: 0,
      created_utc: hours(1),
      likes: null,
      is_submitter: false,
      distinguished: null,
      stickied: false,
      collapsed: false,
    },
    {
      id: `${postId}_c4`,
      author: 'sqlite_defender',
      body: 'Why did you switch from SQLite to Postgres? For a personal project SQLite is often more than enough and has way less operational overhead.',
      score: 398,
      replies: [
        {
          id: `${postId}_c4_r1`,
          author: 'op_here',
          body: 'Mainly because I wanted the experience of running Postgres in production. Totally not necessary for this project\'s scale. But I wanted to learn the operational side.',
          score: 445,
          replies: [],
          depth: 1,
          created_utc: mins(50),
          likes: null,
          is_submitter: true,
          distinguished: null,
          stickied: false,
          collapsed: false,
        },
        {
          id: `${postId}_c4_r2`,
          author: 'sqlite_defender',
          body: 'Fair enough! Learning is a valid reason. Carry on.',
          score: 201,
          replies: [],
          depth: 1,
          created_utc: mins(40),
          likes: null,
          is_submitter: false,
          distinguished: null,
          stickied: false,
          collapsed: false,
        },
      ],
      depth: 0,
      created_utc: hours(1),
      likes: null,
      is_submitter: false,
      distinguished: null,
      stickied: false,
      collapsed: false,
    },
    {
      id: `${postId}_c5`,
      author: 'lucia_auth_dev',
      body: 'Glad Lucia worked out for you! Session-based auth is genuinely underused in the modern web. JWTs get way too much hype for use cases where they add complexity without benefit.',
      score: 287,
      replies: [],
      depth: 0,
      created_utc: mins(90),
      likes: null,
      is_submitter: false,
      distinguished: null,
      stickied: false,
      collapsed: false,
    },
    {
      id: `${postId}_c6`,
      author: 'weekend_project_club',
      body: 'This is the kind of project scope I always aim for on weekends but somehow it always expands into a 3-month endeavor. How did you keep yourself from scope creeping?',
      score: 156,
      replies: [
        {
          id: `${postId}_c6_r1`,
          author: 'op_here',
          body: 'Hard deadline: I had plans Sunday evening. Necessity is the mother of shipping.',
          score: 892,
          replies: [],
          depth: 1,
          created_utc: mins(70),
          likes: null,
          is_submitter: true,
          distinguished: null,
          stickied: false,
          collapsed: false,
        },
      ],
      depth: 0,
      created_utc: mins(120),
      likes: null,
      is_submitter: false,
      distinguished: null,
      stickied: false,
      collapsed: false,
    },
  ];
  return templates;
}

const COMMENT_CACHE: Record<string, Comment[]> = {};

export function getMockComments(postId: string): Comment[] {
  if (!COMMENT_CACHE[postId]) {
    COMMENT_CACHE[postId] = makeComments(postId);
  }
  return COMMENT_CACHE[postId];
}

export function getMockPost(postId: string): Post | undefined {
  return [...MOCK_POSTS, ...MOCK_POSTS_PAGE2].find(p => p.id === postId);
}

export function getMockSubredditPosts(
  subreddit: string,
  page: number,
): {posts: Post[]; after: string | null} {
  const filtered =
    subreddit === 'popular' || subreddit === 'all' || subreddit === 'home'
      ? [...MOCK_POSTS, ...MOCK_POSTS_PAGE2]
      : [...MOCK_POSTS, ...MOCK_POSTS_PAGE2].filter(
          p => p.subreddit.toLowerCase() === subreddit.toLowerCase(),
        );

  const PAGE_SIZE = 10;
  const start = page * PAGE_SIZE;
  const slice = filtered.slice(start, start + PAGE_SIZE);
  const after = start + PAGE_SIZE < filtered.length ? `page${page + 1}` : null;

  return {posts: slice, after};
}

export function getMockSubreddit(name: string): Subreddit | undefined {
  return MOCK_SUBREDDITS.find(
    s => s.displayName.toLowerCase() === name.toLowerCase(),
  );
}

// Simulate network latency
export function delay(ms = 400): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
