# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Roddit' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        end
        # iOS 26 SDK declares clockid_t as an enum; Xcode 26 clang promotes
        # -Wdeprecated-literal-operator to an error. Apply fixes globally,
        # with the extra Yoga flag appended for that target specifically.
        cxx_flags = '$(inherited) -DFOLLY_HAVE_CLOCK_GETTIME=1'
        cxx_flags += ' -Wno-deprecated-literal-operator' if target.name == 'Yoga'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = cxx_flags
        config.build_settings['OTHER_CFLAGS'] = '$(inherited) -DFOLLY_HAVE_CLOCK_GETTIME=1'
      end
    end
  end
end
